### ISSUE TITLE
update docker file to include new opendxl-console

### ISSUE THREAD

**Issue by shadowbq** [opendxl/opendxl-broker#4]
Update the docker file to include new opendxl-console version `2.0`

```dockerfile
 && pip install dxlconsole==0.1.3
```

https://github.com/opendxl/opendxl-console/releases/tag/0.2.0

**Comment by chrissmith-mcafee** [comment]
A revised version of the OpenDXL broker is currently being developed. The new version includes the latest version of the console (0.2.0 at this time).

**Comment by jbarlow-mcafee** [comment]
As part of the new `0.2.0` release of the OpenDXL broker, we upgraded the OpenDXL console dependency to the latest version, 0.2.2. Closing out this issue.
